# Site settings
timezone: America/Chicago

baseurl: '' # the subpath of your site, e.g. /blog/
url: 'https://fereshtehamini.github.io/' # the base hostname & protocol for your site

title: 'Fereshteh Amini'
author: 'Fereshteh Amini'

languages: [ 'en' ]

google_font_sans_serif: 'Source+Sans+Pro:300'

#flickr_user: '131006004@N06'
#flickr_api_key: adb4be93419edab991522b4fa92b7029

#default_header_img_dimensions: 'width="1024" height="1024"'
default_header_img_dimensions: 'width="768" height="768"'
default_thubmnail_img_dimensions: 'width="768" height="768"'

# Handling Reading
safe: true
encoding: utf-8

# Build settings
markdown: kramdown

# Outputting
exclude: [
  'cibuild',
  'Gemfile',
  'Gemfile.lock',
  'package.json',
  'README.md',
  'vendor']

defaults:
  - scope:
      path: ''
    values:
      lang: en
      description: 'Personal website of Fereshteh Amini, an information visualization researcher. It enlists her publications, projects, teachings, services, and contact information.'
  - scope:
      path: 'en'
    values:
      lang: en

# CSS Minification
sass:
  style: compressed
